url: 'http://localhost:8082'

mongodb:
  server:   localhost
  database: uptime
  user:     root
  password: root
  connectionString:   # alternative to setting server, database, user and password separtely
